#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
#discord.gg/pyr0
#instagram: c4gwn 
import keyboard
import random
choice = random.randint(1,10) 
waittime = random.randint(1,15)
lolxd = random.randint(94893,989493)
import pyautogui
from tkinter import * 
from tkinter import messagebox
messagebox.showinfo("SUCCESS", "Starting in 5 seconds. Please press OK and back to game window. Press CTRL+C to CANCEL.")
import time
import os
os.system('cls')
print("5")
time.sleep(1)
os.system('cls')
print("4")
time.sleep(1)
os.system('cls')
print("3")
time.sleep(1)
os.system('cls')
print("2")
time.sleep(1)
os.system('cls')
print("1")
time.sleep(1)
os.system('cls')
print("0")
time.sleep(1)
gunselect = random.randint(1,3) 
while True:
    time.sleep(1)
    pyautogui.click(button='left', clicks=3, interval=0.25)
    time.sleep(1111)
    keyboard.press('w')
    time.sleep(waittime)
    keyboard.release('w')
    keyboard.press('a')
    time.sleep(waittime)
    keyboard.release('a')

    keyboard.press('s')
    time.sleep(waittime)
    keyboard.release('s')
    keyboard.press('space')
    time.sleep(waittime)
    keyboard.release('space')
    keyboard.press('control')
    time.sleep(waittime)
    keyboard.release('control')
    keyboard.press_and_release(gunselect)
    keyboard.press_and_release(gunselect)
    keyboard.press_and_release(gunselect)
    
#you can add more !